### ISSUE TITLE
TCODConsole::print(int x, int y, const std::string &str) unicode exception std::logic_error

### ISSUE THREAD

**Issue by JasonMarechal25** [libtcod/libtcod#33]
Hello,
The following line produce a std::logic_error
`TCODConsole::root->print(x + width / 2, y, std::string("plop");` produce a std::logic_error
When I use c string like:
`TCODConsole::root->print(x + width / 2, y, "plop";`
or 
`TCODConsole::root->print(x + width / 2, y, std::string("plop").c_str();`
I don't get the error.

The full stack is :

```
 	KernelBase.dll!00007ffe2a11a839()	Inconnu
 	[Code externe]	
>	libtcod.dll!tcod::console::UnicodeIterator::parse_unicode() Ligne 895	C++
 	[Cadre en ligne] libtcod.dll!tcod::console::UnicodeIterator::operator++() Ligne 824	C++
 	[Cadre en ligne] libtcod.dll!tcod::console::FormattedUnicodeIterator::operator++() Ligne 932	C++
 	libtcod.dll!tcod::console::next_split_(tcod::console::FormattedUnicodeIterator it, const tcod::console::UnicodeIterator & end, int max_width, int can_split) Ligne 1051	C++
 	libtcod.dll!tcod::console::print_internal_(TCOD_Console & con, int x, int y, int width, int height, const std::string & string, const TCOD_ColorRGB * fg, const TCOD_ColorRGB * bg, TCOD_bkgnd_flag_t flag, TCOD_alignment_t align, int can_split, int count_only) Ligne 1109	C++
 	[Cadre en ligne] libtcod.dll!tcod::console::print(TCOD_Console * con, int fg, int bg, const std::string &) Ligne 1183	C++
 	[Cadre en ligne] libtcod.dll!TCODConsole::print(int) Ligne 278	C++
 	libtcod.dll!TCODConsole::print(int x, int y, const std::string & str) Ligne 275	C++

```

I'm developing on Windows with my system set in French.

Source code is available at https://gitlab.com/JasonMarechal25/roguemanager/tree/feature/GUI

**Comment by HexDecimal** [comment]
The full stack should also include your own calls.  It would be nice to know the message of the `std::logic_error` exception and the actual string passed to `TCODConsole::print` which caused the error.

`TCODConsole::print(int x, int y, const std::string &str)` and
`TCODConsole::printf(int x, int y, const const char *fmt, ...)` expect a UTF8 encoded string.
`TCODConsole::print(int x, int y, const char *fmt, ...)` expects an EASCII encoded string.

I'm guessing you called the UTF8 functions with an EASCII character.  This would cause the UTF8-to-Unicode parser to fail in this manner.

**Comment by JasonMarechal25** [comment]
Details of the exception:
Exception non gérée à 0x00007FFE2A11A839 dans RogueManager.exe : exception Microsoft C++ : std::logic_error à l'emplacement de mémoire 0x0000005D84F9F4E0. a eu lieu 

Full stack:
`>	libtcod.dll!tcod::console::UnicodeIterator::parse_unicode() Ligne 895	C++
 	[Cadre en ligne] libtcod.dll!tcod::console::UnicodeIterator::operator++() Ligne 824	C++
 	[Cadre en ligne] libtcod.dll!tcod::console::FormattedUnicodeIterator::operator++() Ligne 932	C++
 	libtcod.dll!tcod::console::next_split_(tcod::console::FormattedUnicodeIterator it, const tcod::console::UnicodeIterator & end, int max_width, int can_split) Ligne 1051	C++
 	libtcod.dll!tcod::console::print_internal_(TCOD_Console & con, int x, int y, int width, int height, const std::string & string, const TCOD_ColorRGB * fg, const TCOD_ColorRGB * bg, TCOD_bkgnd_flag_t flag, TCOD_alignment_t align, int can_split, int count_only) Ligne 1109	C++
 	[Cadre en ligne] libtcod.dll!tcod::console::print(TCOD_Console * con, int fg, int bg, const std::string &) Ligne 1183	C++
 	[Cadre en ligne] libtcod.dll!TCODConsole::print(int) Ligne 278	C++
 	libtcod.dll!TCODConsole::print(int x, int y, const std::string & str) Ligne 275	C++
 	RogueManager.exe!GUI::renderBar(int x, int y, int width, std::string name, float value, float maxValue, TCODColor barColor, TCODColor backColor) Ligne 69	C++
 	RogueManager.exe!GUI::render() Ligne 39	C++
 	RogueManager.exe!Engine::render() Ligne 59	C++
 	RogueManager.exe!main() Ligne 17	C++
`

I don't think I used any special character. The call is really with the string "plop" :
`TCODConsole::root->print(x + width / 2, y, std::string("plop");
`

I'll add the local variables after the exception was thrown:

  | Nom | Valeur | Type
-- | -- | -- | --
▶ | &codepoint_ | 0x0000005d84f9f688 {-1} | int *
  | code_size_ | -3 | __int64
▶ | end_ | 0xcccccd2a51c6c4b4 <Erreur durant la lecture des caractères de la chaîne.> | const unsigned char *
▶ | p_ | 0x0000005d84f9f7e9 "Áýf\b\x2" | const unsigned char *
▶ | this | 0x0000005d84f9f678 {p_=0x0000005d84f9f7e9 "Áýf\b\x2" end_=0xcccccd2a51c6c4b4 <Erreur durant la lecture des caractères de la chaîne.> ...} | tcod::console::UnicodeIterator *

**Comment by HexDecimal** [comment]
Thanks for adding more detail and clarifying about the string used.

> end_ = 0xcccccd2a51c6c4b4

This could be the issue.  It kind of looks like half of this pointer is uninitialized and the other half might be garbage data.

I'll fix this as soon as I can get to it.

**Comment by HexDecimal** [comment]
I haven't been able to reproduce the error.  I don't know if I accidentally fixed it, if I'm not testing for the right thing, or if it's based on the environment somehow.

I've released libtcod version 1.15.0;  I'd like you to try to get it to crash and if it does then save the commit and link me to it so I can inspect it more carefully.

**Comment by JasonMarechal25** [comment]
I still have the crash happening. I've push an example on a [separated branch](https://gitlab.com/JasonMarechal25/roguemanager/commit/99844d46f5019debde4b03a5daa6b785b4ffbc95) .
I'm building my project with the visual studio toolchain. I'm using precompiled library for x86_64 and my target is x64 debug (on VS 2019)

Call to TCodeConsolePrint is done in Engine constructor so early. If you can compile and run it, it should crash immediately.

I've opened libtcod.sln and tried to print in the frost example. The call to _TCODConsole::root->print(0 , 0, std::string("plop");_ pass properly.

**Comment by InvisiblePhil** [comment]
I think I have the answer - when using MSVC in debug builds std::string is 40 bytes long, but it is 32 bytes in release builds (though I cannot yet comment why). This causes undefined behaviour upon certain operations, i.e. this crash.

Running your project in x64-Release works. A possible solution would be to not mix debug and release DLL's; use a debug DLL of libtcod for debug builds of your project and release builds for release.

I also have a cautionary observation that your project is using VS 2019/MSVC 14.23 - whereas libtcod is compiled targetting the VS 2017/MSVC 14.16. This means that STL types in your compiled projects may be different from those compiled into the libtcod DLL. Microsoft do promise binary compatibility between these STL versions and so this may not manifest any issues, but I still tend to just compile everything from source in the same compiler & STL version so I don't have to worry.

This is why a common recommendation with C++ is to have external/exported API's contain no STL types. I've also seen the alternative - to enforce a single compiler & STL version across an entire company.

**Comment by HexDecimal** [comment]
That'd be consistent with what I've been experiencing.  I was able to reproduce the error with release dll's, but not with debug ones.  When I switch to release mode it works without issues.  When searching I found mentions of the std::string size, but I didn't make the connection, I'm glad you were able to explain it.

I'm not really sure what I should do about this.

**Comment by InvisiblePhil** [comment]
I don't think there's a nice solution. All I can think of are:

1. Officially release Debug and Release DLL's and tell people not to mix and match
2. Tell people to compile from source if running against debug builds
3. Make clever/hacky changes to the API to avoid using STL types across DLL boundaries, but instead use intermediate types which implicitly convert from STL types and perform any necessary pointer arithmetic via inline functions so that consumers' compilers will produce code that is correct for their STL & compiler.

I've made a horrific hack for point 3 above to prove to myself that it works (it does fix this crash when using a release libtcod with debug exe). I can turn it into a branch on an actual fork if that would help demonstrate how odd the change would be. 

An aside, from what I understand of the STL I've just read, the reason for the 8-byte difference is an extra pointer that is stored when in debug mode to enable extra checks on iterator validity.

**Comment by HexDecimal** [comment]
I can imagine how to do 3, but I'll likely pick one of the first two options.  I want to minimize special edge-case code.

I wonder if `std::string_view` also has this issue.

**Comment by JasonMarechal25** [comment]
Indeed, I've tried with my own libtcod build dll and it works. Thank you.

**Comment by HexDecimal** [comment]
Adding overloads which take `std::string` to the dll exported functions turned out to be a bad idea.  These will be officially replaced with the `tcod::print` functions which perform inline calls to the C API and won't suffer similar issues.
