### ISSUE TITLE
Credits functions: bad access when the root console isn't initilized.

### ISSUE THREAD

**Issue by HexDecimal** [libtcod/libtcod#87]
The credits functions, at least `TCOD_console_credits_render`, seem to perform a bad access when the root console isn't initialized.  This can easily happen when switching a program to use contexts.

I don't know any more details yet, but it's something I'll need to look into.  I can only assume that one of the functions called by it does not expect a NULL root console, but I can't be certain it isn't something else.

**Comment by hazeled** [comment]
It looks like this is fixed, now it just fails with an assert `con` failed

**Comment by HexDecimal** [comment]
It's still an issue as long as the credits continue to use `NULL` to reference the console which has been deprecated across the library.

This might fail an assert on debug mode and crash in release mode.

**Comment by HexDecimal** [comment]
Added `TCOD_console_credits_render_ex`, this function takes a console directly.

**Comment by HexDecimal** [comment]
All credits functions other than `TCOD_console_credits_render_ex` have been deprecated.
